### ISSUE TITLE
Permissions backend ./. contentelement

### ISSUE THREAD

**Issue by donnnnar** [fabarea/media#154] opened 2016-10-10 11:46 UTC
Hi,

we're using the media extension, to get a better overview of the media elements and it works very well. 

One of our users told us an problem: if the user lists all the media files in the backend plugin, he got 11.716 entries. If the user open the media element via plugin (f.e. site > config > resources > new relation), he got only 415 entries.

I've located this misdemeanour in the function "\Fab\Media\Security\FilePermissionsAspect::addFilePermissionsForFileStorages()":

Code 1:

```
if ($this->getModuleLoader()->hasPlugin() && !$this->getCurrentBackendUser()->isAdmin()) {

$fileMounts = $this->getCurrentBackendUser()->getFileMountRecords();
    $collectedFiles = array();
    foreach ($fileMounts as $fileMount) {

        $combinedIdentifier = $fileMount['base'] . ':' . $fileMount['path'];
        $folder = ResourceFactory::getInstance()->getFolderObjectFromCombinedIdentifier($combinedIdentifier);

        $files = $this->getFileUids($folder);
        $collectedFiles = array_merge($collectedFiles, $files);
    }

    $matcher->in('uid', $collectedFiles);
}

```

Why is this code only be used in the plugins? Isn't it better to do execute the code, only if the user isn't the admin? And why do we get only the files in the mounted folders? Why isn't it recursive? My proposal:

Code 2:

```
/**
 * @param Folder $folder
 * @return array
 */
protected function getFileUids(Folder $folder) {
    $files = array();
    // load files recursive
    $folders = $folder->getFiles(0, 0, \TYPO3\CMS\Core\Resource\Folder::FILTER_MODE_USE_OWN_AND_STORAGE_FILTERS, TRUE);
    foreach ($folders as $file) {
        $files[] = $file->getUid();
    }
    return $files;
}
```

My wish is also, to execute "code 1", only if we set this in extension configuration. F.e.:

ext_conf_template.txt:

```
# cat=basic//; type=boolean; label= If true, the files will only be shown, if the user got the file mounts
use_file_permissions = 0
```

\Fab\Media\Module\MediaModule:

```
public function useFilePermissions() {
        $configuration = $this->getModuleConfiguration();
        return (bool)$configuration['use_file_permissions']['value'];
}
```

\Fab\Media\Security\FilePermissionsAspect::addFilePermissionsForFileStorages:

```
                if ($this->getModuleLoader()->useFilePermissions()
                    && !$this->getCurrentBackendUser()->isAdmin()) {

                    $fileMounts = $this->getCurrentBackendUser()->getFileMountRecords();
                    $collectedFiles = array();
                    foreach ($fileMounts as $fileMount) {

                        $combinedIdentifier = $fileMount['base'] . ':' . $fileMount['path'];
                        $folder = ResourceFactory::getInstance()->getFolderObjectFromCombinedIdentifier($combinedIdentifier);

                        $files = $this->getFileUids($folder);
                        $collectedFiles = array_merge($collectedFiles, $files);
                    }

                    $matcher->in('uid', $collectedFiles);
                }
```

**Comment by mbrodala** [comment] 2016-10-18 13:55
This is most likely a duplicate of #150

**Comment by fabarea** [comment] 2016-10-19 11:48
Sorry for the delay. I am going to release the bugfix today.

**Closed as completed by fabarea** 2016-10-19 11:48 UTC
